config/routes.rb
Invoicer::Application.routes.draw do

  post '/update_pass/', to: 'users#update_pass', as: 'update_password'
  post '/set_current_company/:company_id', to: 'users#set_current_company', as: 'set_current_company'
  resources :users
  resources :invoices do
    resources :charges
  end
  resources :relations
  resources :sessions
  resources :charges
  resources :companies

  get '/invoicesreceived', to: 'invoices#received'
  get '/invoicessent', to: 'invoices#sent'

  resource :password_reset

  root to: 'root#index'

end

app/controllers/password_resets_controller.rb
class PasswordResetsController < ApplicationController
  skip_before_filter :logged_in?
  layout "login"
  def new
  end

  def edit
    @user = User.find_by_password_reset_token(params[:password_reset_token])
    unless @user
      flash[:error] = "Fuck off"
      redirect_to new_session_url
    end
  end

  def create
    @user = User.find_by_email(params[:email])
    if @user
      @user.send_password_reset_token
    end
    flash[:notice] = "Email Sent"

    redirect_to new_session_url
  end

end

app/helpers/password_resets_helper.rb
module PasswordResetsHelper
end

app/views/password_resets/edit.html.erb
<h1>Update Password</h1>
<form action="<%= update_password_url(@user) %>" method="post" >
  <%= auth %>
  <input type="hidden" name="password_reset_token" value="<%= @user.password_reset_token %>" >

	<roundform>
		<input type='password' name='user[password]' placeholder='password'>
	</roundform>
  <label>Update password
    <input type='submit' value='Update password'>
  </label>
</form>

app/views/password_resets/new.html.erb
<h1>Reset password</h1>
<form action="<%= password_reset_url %>" method="post">
  <%= auth %>
	<roundform>
		<input type='email' name='email' placeholder='email'>
	</roundform>
<input type="submit" value="Reset Password">
</form>