config/routes.rb
Invoicer::Application.routes.draw do

  post '/update_pass/', to: 'users#update_pass', as: 'update_password'
  post '/set_current_company/:company_id', to: 'users#set_current_company', as: 'set_current_company'
  resources :users
  resources :invoices do
    resources :charges
  end
  resources :relations
  resources :sessions
  resources :charges
  resources :companies

  get '/invoicesreceived', to: 'invoices#received'
  get '/invoicessent', to: 'invoices#sent'

  resource :password_reset

  root to: 'root#index'

end

app/models/invoice.rb
class Invoice < ActiveRecord::Base
  attr_accessible :description, :due_date, :issue_date, :issuer_id, :sender_id, :receiver_id

  has_many( :charges,
  class_name: "Charge",
  foreign_key: :invoice_id,
  primary_key: :id)

  belongs_to(:sender,
  class_name: "Company",
  foreign_key: :sender_id,
  primary_key: :id)

  belongs_to(:receiver,
  class_name: "Company",
  foreign_key: :receiver_id,
  primary_key: :id)

  def total
    self.charges.sum{|charge| charge.amount}
  end


end

app/controllers/invoices_controller.rb
class InvoicesController < ApplicationController
  def index
    begin
      @invoices_sent = Invoice.find_all_by_sender_id(current_company.id)
      @invoices_received = Invoice.find_all_by_receiver_id(current_company.id)
    rescue
      @invoices_sent = []
      @invoices_received = []
      flash.now[:error] = "Your company is not set"
    end
  end


  def sent
    render json: Invoice.find_all_by_sender_id(current_company.id)
  end

  def received
    render json: Invoice.find_all_by_receiver_id(current_company.id)
  end

  def new
    if current_company
    	@invoice = Invoice.new
    	@company = current_company
      @relationships = (@company.billers + @company.debtors).uniq
      @users = User.all
    end
  end

  def create
    # Cover your ass here.
  	@invoice = Invoice.new(params[:invoice])
    @invoice.charges.new(params[:charges].values)
    @invoice.sender_id = current_company.id
  	@invoice.save!
  	redirect_to invoices_url
  end

  def show
  	@invoice = Invoice.find(params[:id])
  end

end

app/helpers/invoices_helper.rb
module InvoicesHelper
end

app/views/invoices/_form.html.erb
<input type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">
<p>
 <label>Description
   <input name="invoice[description]" type="textarea" />
 </label>
</p>
<p>
 <label>Sender:
   <span><%= current_company.name %></span>
   <%= link_to "Change Company"%>
  </label>
</p>
<p>
 <label>Client
   <!-- <input name="invoice[receiver_id]" type="integer" /> -->
   <select name="invoice[receiver_id]">
      <% @relationships.each do |company| %>
       <option value="<%= company.id %>">
      <%= company.name %>
     </option>
     <% end %>
   </select>
 </label>
 <%= link_to "New Client", new_relation_url %>
</p>
<p>
 <label>Sent Date
   <input name="invoice[issue_date]" type="date" value=<%= Date.today %> />
 </label>
</p>
<p>
 <label>Due Date
   <input name="invoice[due_date]" type="date" value=<%= (Date.today+60.days) %> />
 </label>
</p>
<hr>
<div id="charge_form">
<p>
   <label>Description
     <input name="charges[1][description]" type="textarea" />
   </label>
  </p>
  <p>
   <label>Amount
     <input name="charges[1][amount]" type="integer" />
   </label>
  </p>
</p>
</div>

app/views/invoices/edit.html.erb
<h1>Edit Invoice</h1>
<form action="<%= invoices_url %>" method='post'>

<%= render "/invoices/form"%>

  <button type='submit'>Reconsider?</button>
</form>

app/views/invoices/new.html.erb
<h1>New Invoice</h1>
<form action="<%= invoices_url %>" method='post'>
  <% if current_company %>
    <%= render "/invoices/form"%>
  <% else %>
  <p>
    Please pick or create a company in your <%= link_to "profile", edit_user_url(current_user.id) %>
  </p>
  <% end %>
  <button type='submit'>Charge the Bastards</button>
</form>

app/views/invoices/show.html.erb
<h1><%= @invoice.description %> </h1>

<p>
	Issued: <%= @invoice.issue_date %>
</p>
<p>
	Due: <%= @invoice.due_date %>
</p>
<p>
	Sender: <%= Company.find(@invoice.sender_id).name %>
</p>
<p>
	Receiver: <%= Company.find(@invoice.receiver_id).name %>
</p>

<% total = 0 %>

<ul>
	<% @invoice.charges.each do |charge| %>
	<% total += charge.amount %>
	<li>
		<hr>
		<p>
			<%= link_to charge.description, charge %>
		</p>
		<p>
			<%= format_dec(charge.amount) %>
		</p>
	</li>
	<% end %>
	<hr>
	TOTAL: <%= format_dec(total) %>
</ul>