config/routes.rb
Invoicer::Application.routes.draw do

  post '/update_pass/', to: 'users#update_pass', as: 'update_password'
  post '/set_current_company/:company_id', to: 'users#set_current_company', as: 'set_current_company'
  resources :users
  resources :invoices do
    resources :charges
  end
  resources :relations
  resources :sessions
  resources :charges
  resources :companies

  get '/invoicesreceived', to: 'invoices#received'
  get '/invoicessent', to: 'invoices#sent'

  resource :password_reset

  root to: 'root#index'

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :addr1, :addr2, :country, :current_company_id, :fname, :lname, :state,
  :zip, :password_digest, :password, :email, :session_token, :city

  has_many(:company_positions,
  class_name: "Employee",
  foreign_key: :user_id,
  primary_key: :id)

  has_many( :companies,
  through: :company_positions,
  source: :company)




  def self.find_by_credentials(email,password)
    user = User.find_by_email(email)
    msg = 'User Not Found'
    raise StandardError, msg unless user
    msg =  'Invalid Login'
    raise StandardError, msg unless user.is_password?(password)

    user
  end

  def self.generate_token
    SecureRandom::urlsafe_base64(16)
  end

  def has_session_token
    if self.session_token.nil?
      reset_session_token
    end
  end

  def reset_session_token
    self.session_token = self.class.generate_token
    self.save!
  end

  def send_password_reset_token
    @reset_password_token = User.generate_token
    @password_reset_sent_at = Time.now
    self.save!

    UserMailer.password_reset(self).deliver!
  end
  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
    #self.password_digest == BCrypt::Password.new(password)
  end

  def as_json(user)
    hash = self.attributes
    hash.except!( 'password_digest', 'password',  'session_token')
    hash[:currentCompany] = Company.find(self.current_company_id)

    {
      user: hash,
      companies: self.companies
    }
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_filter :logged_in?, :only => [:new, :create]

  layout "login", only: [:new]


  def index

  end

  def create
    @user = User.new(params[:user])

    if @user.save
      msg = UserMailer.welcome_email(@user)
      msg.deliver!
      login_user!(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def new
    @user = User.new
  end

  def show
    render json: current_user
  end

  def edit
    @user = User.find(params[:id])
  end

  def update_pass
    begin
      @user = User.find_by_password_reset_token(params[:password_reset_token])
      @user.password_reset_token = User.generate_token
      @user.password = params[:password]
      @user.save
      flash[:notice] = "Password Updated"
    rescue
      flash[:error] = "Fuck off"
    end
    redirect_to new_session_url
  end

  def update
    @user = current_user
    if @user
      @user.update_attributes(params[:user])
      flash[:notice] = "Updated"
      redirect_to root_url
    else
      redirect_to new_session_url
    end
  end

  def set_current_company
    # Add validation for actually being with the company
    current_user.current_company_id = params[:company_id]
    current_user.save!
    @user = current_user
    flash[:notice] = 'Current Company Updated'
    redirect_to edit_user_url(current_user.id)
  end

end

app/helpers/users_helper.rb
module UsersHelper
  def current_company
    return nil if current_user.current_company_id.nil?
    @current_company ||= Company.find(current_user.current_company_id)
    #
  end

end

app/views/users/edit.html.erb
<h1><%= @user.email %></h1>
<input type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">
<label>Email
  <input name="user[email]" type="email" value="<%= @user.email %>"/>
</label>


<h3>Current Company</h3>
<p>Your current company is <%= current_company.nil? ? 'unset' : current_company.name %></p>

<h2>Companies</h2>
<ul>
<% @user.companies.each do |company| %>
  <table>
    <tr>
    <td><%= link_to company.name, company %></td>
    <td>
      <% unless current_company == company %>
      <%= button_to "Make Current Company", set_current_company_url(company.id) %>
      <% end %>
    </td>
  </tr>
  </table>
<% end %>
</ul>

app/views/users/new.html.erb
<h3>Sign Up</h3>
<form action='/users' method='post'>
  <input type="hidden"
          name="authenticity_token"
          value="<%= form_authenticity_token %>">
	<roundform>
		<input type='email' name='user[email]' placeholder='email'>
		<input type='password' name='user[password]' placeholder='password'>
	</roundform>
	<button type='submit' 
    class='submit'>Sign Up</button>
</form>
<a href='<%= new_session_url %>'>Or Log In!</a>

app/views/users/show.html.erb
<h1><%= @user.email %></h1>

<ul>
<% @user.companies.each do |company| %>
  <li>
    <%= link_to company.name, company %>
  </li>
<% end %>
</ul>