config/routes.rb
Invoicer::Application.routes.draw do

  post '/update_pass/', to: 'users#update_pass', as: 'update_password'
  post '/set_current_company/:company_id', to: 'users#set_current_company', as: 'set_current_company'
  resources :users
  resources :invoices do
    resources :charges
  end
  resources :relations
  resources :sessions
  resources :charges
  resources :companies

  get '/invoicesreceived', to: 'invoices#received'
  get '/invoicessent', to: 'invoices#sent'

  resource :password_reset

  root to: 'root#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
  attr_accessible :addr1, :addr2, :country, :name, :state, :zip, :city


  has_many(:employee_relations,
  class_name: "Employee",
  foreign_key: :company_id,
  primary_key: :id)

  has_many(:owner_relations,
  class_name: "Employee",
  foreign_key: :company_id,
  primary_key: :id,
  conditions: {owner: true}
  )


  has_many(:employees, through: :employee_relations, source: :employee)

  has_many(:owners,
  through: :owner_relations,
  source: :employee)

  has_many(:invoices_sent,
  class_name: "Invoice",
  foreign_key: :sender_id,
  primary_key: :id)

  has_many(:invoices_received,
  class_name: "Invoice",
  foreign_key: :receiver_id,
  primary_key: :id)

  has_many(:sender_relations,
  class_name: "Relation",
  foreign_key: :sender_id,
  primary_key: :id)

  has_many( :debtors,
  through: :sender_relations,
  source: :receiver)

  has_many(:receiver_relations,
  class_name: "Relation",
  foreign_key: :receiver_id,
  primary_key: :id)

  has_many( :billers,
  through: :receiver_relations,
  source: :sender)

  # def as_json
#     {
#       company: self.id
#     }
#   end

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  def new
    @company = Company.new
    respond_with(@company) do |format|
      format.json { render json: @company }
      format.html
    end
  end

  def edit
    @company = Company.find(params[:id])
  end

  def create
    @company = Company.create(params[:company])
    if @company.save
      Employee.create({
        company_id: @company.id,
        owner: true,
        user_id: current_user.id
      })
      redirect_to @company

    else
      flash.now[:errors] = @company.errors.full_messages
      render :new
    end
  end

  def index
    @companies = current_user.companies
    respond_with(@companies) do |format|
      format.json { render json: @companies }
      format.html
    end
  end


  def show
    @company = Company.find(params[:id])
  end

end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<input type="hidden"
        name="authenticity_token"
        value="<%= form_authenticity_token %>">
<p>
 <label>Name
   <input name="company[name]" type="text" />
 </label>
</p>
<p>
 <label>Address
   <input name="company[addr1]" type="text" />
   <br>
   <input name="company[addr2]" type="text" />
  </label>
</p>
<p>
 <label>State
   <input name="company[state]" type="text" />
  </label>
</p>
<p>
 <label>Country
   <input name="company[country]" type="text" />
  </label>
</p>
<p>
 <label>Zip
   <input name="company[zip]" type="text" />
  </label>
</p>
<!-- add owner management and employee management -->

app/views/companies/edit.html.erb
<h1>Edit <%= @company.name %></h1>
<form action="<%= companies_url %>" method='post'>
  <input type='hidden' value='put' name='_method' >

<%= render "form"%>

  <button type='submit'>Create Company</button>
</form>

app/views/companies/index.html.erb
<h1>Your Companies</h1>
<ul>
<% @companies.each do |company| %>
<hr>
<li> <%= link_to company.name, company %></li>
<% end %>
</ul>

<p>
  <%= link_to "Make new Company", new_company_url %>
</p>

app/views/companies/new.html.erb
<h1>New Company</h1>
<form action="<%= companies_url %>" method='post'>

<%= render "form"%>

  <button type='submit'>Create Company</button>
</form>

app/views/companies/show.html.erb
<p>
 <label>Name
   <%= @company.name %>
 </label>
</p>
<p>
 <label>Address
   <%= @company.addr1 %>
   <br>
   <%= @company.addr2 %>
  </label>
</p>
<p>
 <label>State
   <%= @company.state %>
  </label>
</p>
<p>
 <label>Country
   <%= @company.country %>
  </label>
</p>
<p>
 <label>Zip
   <%= @company.zip %>
 </label>
</p>

<ul>
  <% @company.employees.each do |employee| %>
  <li>
    <%= link_to employee.email, employee %>
  </li>
  <% end %>
</ul>